# CripCraft local prototype server properties
accepts-transfers=false
allow-flight=true
enable-command-block=true
enable-query=false
enable-rcon=false
enforce-secure-profile=false
gamemode=adventure
generate-structures=true
hardcore=false
hide-online-players=false
level-name=cripcraft_world
level-seed=CripCraftPrototype
level-type=minecraft:normal
max-players=8
max-tick-time=60000
motd=\u00A70[\u00A73CripCraft\u00A70] \u00A7bDark Neon Prototype \u00A78| \u00A7aLocal Test
difficulty=normal
network-compression-threshold=256
online-mode=true
player-idle-timeout=0
pvp=false
require-resource-pack=false
resource-pack=
server-ip=
server-port=25565
simulation-distance=8
spawn-monsters=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
